const IS_WEBPACKED = 'IS_WEBPACKED';

const PRODUCTION = 'PRODUCTION';
const DEVELOPMENT = 'DEVELOPMENT';
const VERSION = 'VERSION';

const GIT_VERSION = 'GIT_VERSION'
const GIT_COMMIT_HASH = 'GIT_COMMIT_HASH'
const GIT_BRANCH = 'GIT_BRANCH'
const GIT_LAST_COMMIT_DATETIME = 'GIT_LAST_COMMIT_DATETIME'

export {
  IS_WEBPACKED,

  DEVELOPMENT,
  PRODUCTION,
  VERSION,

  GIT_VERSION,
  GIT_COMMIT_HASH,
  GIT_BRANCH,
  GIT_LAST_COMMIT_DATETIME
}

const WebpackDefines = {
  IS_WEBPACKED,

  DEVELOPMENT,
  PRODUCTION,
  VERSION,

  GIT_VERSION,
  GIT_COMMIT_HASH,
  GIT_BRANCH,
  GIT_LAST_COMMIT_DATETIME
}

export default WebpackDefines;